### PR TITLE
correct form of [Symbol.iterator]

### PR DESCRIPTION
**Pull request by benwest**
hotfix! i didn't implement this quite right before. esoteric stuff!

### CODE REVIEW

**Comment by hamzakubba** [comment]
Would be nice to add a test case that this fixes, if that's easy enough (from my one PR, the tests seem easy to add to, fwiw).

**Comment by hmans** [comment]
I agree with @hamzakubba. May I ask you to add a test case? Thanks!

**Comment by benwest** [comment]
absolutely!

**Comment by hmans** [comment]
Thank you! I'm on the go until Saturday and will take a look then.

**Pull request merged**
