### PR TITLE
Fix disappearing asteroids and bullets

### PR DESCRIPTION
**Pull request by jure**
This fixes the issue described #287, where the asteroids and bullets disappeared after a while. It turns out they were frustum culled once the player moved too far away from the starting position and the original geometry went out of the camera's frustum. 

I didn't dig into why this has only started happening recently, but I did check out 26d6682, and can confirm that it did not happen there, but also the `InstancedParticles` meshes `frustumCulled` was `false` there, whereas it was/is `true` on latest `main`.

### CODE REVIEW

**Comment by hmans** [comment]
Thank you very much for the PR -- something having changed in the frustum culling behavior of Three.js' `InstancedMesh` sounds like a reasonable explanation for what was going on (but I haven't gone through their changelog yet to confirm this.)

**Comment by hmans** [comment]
I think the build pipeline is just being a little weird, so I'm merging this now.

The other regression I need to look at is the reduction in resolution, this might be anything between the Composer Suite libraries I'm using (Render Composer specifically) and Three.js, possibly `postprocessing`. I really kinda want to get those dependencies out of the React demo and make it just a plain Three.js + R3F thing.

**Comment by jure** [comment]
I think users of the library would appreciate the reduction in moving parts, especially since the demo also serves as documentation, doubly so while things are in flux.

The demo looks really good though, so there's probably room for a separate 'all out' demo of ECS + other technologies you've been developing :)

Thanks for merging!

**Comment by jure** [comment]
Seems like the deployment for the previews works just fine, so I wonder what's up with the main deployment? 

https://miniplex-react-demo-38b86qozt-hmans.vercel.app/

**Pull request merged**
